/*
 * This source file was generated by the Gradle 'init' task
 */
package lab04;

public class App {
    public String getText() {
        return "Laboratório de Testes";
    }

    public static void main(String[] args) {
        System.out.println(new App().getText());
    }
}
